### ISSUE TITLE
Error in the CI job when I use the field `Remotes`

### ISSUE THREAD

**Issue by etiennebacher** [rocker-org/r2u#2]
Hello, I started using `r2u` for CI (following [this blog post](https://dirk.eddelbuettel.com/blog/2023/07/23/#041_simpler_ci_via_r2u)) and it's amazing how fast it is (~1min for the whole CI).

I encountered an issue when I started to use the `Remotes` field in `DESCRIPTION`. For example in this [failed job](https://github.com/etiennebacher/tidypolars/actions/runs/5740283587/job/15557744337), I have the following error:
```
> remotes::install_deps(".", dependencies=TRUE)
Error: Unknown remote type: github
  Cannot find repo pola-rs/r-polars.
cannot open URL 'https://api.github.com/repos/pola-rs/r-polars/releases'
Execution halted
```
but the repo definitely exists and the URL works fine in my browser. I know you're not responsible for `remotes`,  but maybe you already encountered this and found that this is due to the container somehow? Anyway, just close this if this is not the right place to ask, and thanks for `r2u`.

---

My `DESCRIPTION` file if it helps:
```
Imports: 
    polars,
    ...[cut]...
Remotes:
    pola-rs/r-polars@*release
```

**Comment by eddelbuettel** [comment]
Salut Etienne and thanks for trying r2u.  We should probably have had this bug report at the r2u repo rather than here because what you are hitting is a _bspm_ design choice (and hence pretty much a r2u design choice).

As @enchufa2 (over at either the bspm and or r2u repos) has timelessly reminded people, bspm wraps around install.packages.  So it can work for packages that have a commensurate (and hence apt compatible) backend.

remotes is different and falls back straight to source as it does not know about the apt-driven repos r2u uses.  So it is ... a little out of scope for r2u. Sorry.

Your best best is to use a wrapper such the (not quite finalized by working) `installRub.r` (for "install r-universe binary") from `littler` which I have used to stick eg arrow or rpolars onto Ubuntu 22.04 systems.  It complements r2u _perfectly_ (and I may need to write a blog post for it).  Example:

```sh
edd@rob:~$ docker run --rm -ti rocker/r2u installRub.r -u rpolars polars
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]                                                                                                                                                   
Ign https://r2u.stat.illinois.edu/ubuntu jammy InRelease                                                                                                                                                          
Get:2 https://r2u.stat.illinois.edu/ubuntu jammy Release [5713 B]                                                                                                                                                 
Get:3 https://r2u.stat.illinois.edu/ubuntu jammy Release.gpg [793 B]                                                                                                                                              
Get:4 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2321 kB]                                                                                                                                    
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                                                                                                                         
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                                                                                                           
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]                                                                                                                                         
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [7337 kB]                                                                                                                                      
Get:9 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]                                                                                                                                   
Get:10 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]                                                                                                                                  
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]                                                                                                                                       
Get:12 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]                                                                                                                                   
Get:13 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3626 B]                                                                                                                              
Get:14 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [41.5 kB]                                                                                                                              
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1231 kB]                                                                                                                           
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [865 kB]                                                                                                                          
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [49.8 kB]                                                                                                                         
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1093 kB]                                                                                                                               
Get:19 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [25.6 kB]                                                                                                                         
Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [49.4 kB]                                                                                                                             
Get:21 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [848 kB]                                                                                                                        
Get:22 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.0 kB]                                                                                                                       
Get:23 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [977 kB]                                                                                                                          
Get:24 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [824 kB]                                                                                                                              
Fetched 36.0 MB in 0s (0 B/s)                                                                                                                                                                                     
Available system packages as root...
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://rpolars.r-universe.dev/bin/linux/jammy/4.3/src/contrib/polars_0.7.0.9000.tar.gz'
Content type 'application/x-gzip' length 23863019 bytes (22.8 MB)
==================================================
downloaded 22.8 MB

* installing *binary* package ‘polars’ ...
* DONE (polars)

The downloaded source packages are in
        ‘/tmp/downloaded_packages’
edd@rob:~$ 
```

Here `-u rpolars` tells it to look in the `rpolars` universe, and to then install the (binary Ubuntu LTS package) `polars` from it.  (I am wondering if I should rewrite the script to take a single argument `polars@rpolars`, not sure.

So I think you "just" need to wrap this either via this littler script or the direct invocation shown on the polars README.

So given that the question was a little out of scope, yet can be addressed as shown, do you think we can close this?

**Comment by etiennebacher** [comment]
Thank you for the detailed answer, I'll explore this a bit later (or wait for the blog post ;)), I think we can close this

**Comment by eddelbuettel** [comment]
It's a good and fair advanced user question:  how can I use r2u as a _base layer_ on which I can use my _custom_ CI.  So here we need to slide in the one repo / source not provided by r2u and apt that your package in question needs.  So I would just shimmy in a CI step entry as eg

      - name: Add rpolars
        run: Rscript -e 'install.packages("polars", repos = "https://rpolars.r-universe.dev/bin/linux/jammy/4.3")'

before the actual package build and test is done.

**Comment by etiennebacher** [comment]
This is actually [what I did so far](https://github.com/etiennebacher/tidypolars/blob/6f5dfb1596f7f6664706a1026446f2869833a484/.github/workflows/check.yml#L40-L45) but then `tidypolars` can't build on r-universe (https://etiennebacher.r-universe.dev/builds)

**Comment by eddelbuettel** [comment]
Your [yml file](https://github.com/etiennebacher/tidypolars/blob/6f5dfb1596f7f6664706a1026446f2869833a484/.github/workflows/check.yml) has 

    install.packages("https://github.com/pola-rs/r-polars/releases/latest/download/polars__x86_64-pc-linux-gnu.gz",\
           repos = NULL)

which is not what I suggested 

     install.packages("polars", repos = "https://rpolars.r-universe.dev/bin/linux/jammy/4.3")

If you need to debug your CI, what I would do is a) reduce from a matrix of four runs to just one for now, b) add an explicit `Rscript -e 'print(installed.packages())'`, c) maybe remove the `remotes:` line from `DESCRIPTION` and d) most importantly first debug this locally under Docker in a r2u container as that is the true beauty of developing in Docker: it is portable.

**Comment by etiennebacher** [comment]
Ah right, my mistake. I actually never used Docker before so that's gonna be a nice way to start (I hope ^^), thanks

**Comment by eddelbuettel** [comment]
Yes has a learning curve, as other things do, but it is so so worth it.  Inside your work is just standard shell (and what you build on top) which can make it immensely powerful.

**Comment by etiennebacher** [comment]
That was a super suggestion, I often wondered how to test my CI jobs locally and `docker` is great for this kind of stuff

**Comment by eddelbuettel** [comment]
It is indeed, and so much so that I *much* prefer to limit my CI to setups where I can in fact replicate in a container.

[ I actually realized one more possible problem in your setup and the CI yaml I saw yesterday:  You had a (standard usethis AFAIK) matrix with multiple R versions all running on ubuntu-latest.  That will of course fail with r2u as r2u only support r-release.  This may not matter to you if you use RSPM/PPM in the others I just thought it was worth mentioning (which I forgot to do yesterday, busy day...)   Anyway, also congrats on all the good vibes for `tidypolars` which has a lot of people excited.  And I so hope rpolars gets its CRAN issues sorted out. ]

**Comment by eddelbuettel** [comment]
That actually made me curious and indeed you seem to be wasting identical cycles.  Look at this:

![image](https://github.com/rocker-org/r2u/assets/673121/0d37d94b-dac0-4ec3-b27d-1b39317ed9ab)

I highlighted 'R 4.1.3' but because you opt into r2u of course you get its R 4.3.1.  So long story short you cannot mix and match the setup from my blog post for r2u with the usethis setup (beyond maybe in r-release).

**Comment by etiennebacher** [comment]
Aaah indeed, I thought I had just copied your blog post but I forgot that I mixed it with another CI file (https://github.com/etiennebacher/tidypolars/commit/48efdd3a58267898f5e5f25af25ce69742b8e1ba). Btw, the previous one was also one of your files from `r-ci` I think, I copied it from Vincent's CI in `marginaleffects`.

Well, it's a lot of first things with this project: first use of r2u, first docker container, first `tinytest`, etc. I didn't sort everything out regarding R-universe as well, but I'll slowly get there :)

And indeed having `polars` on CRAN would be great, I need to catch up a bit on the last events

**Comment by eitsupi** [comment]
> And indeed having `polars` on CRAN would be great,

Probably almost impossible in the short term....... (https://github.com/pola-rs/r-polars/issues/80#issuecomment-1646735125)

If I understand correctly, it is likely that the entry in the Remotes field is required for R-universe to correctly recognize the polars as a dependency. (like pola-rs/r-polars#72)

**Comment by eddelbuettel** [comment]
(I use r2u _effectively_ in all my CI runs via r-ci.sh; I only recently started to use or show the demo r2u.yaml from the blog post. _If you want easiest r2u use the one from the blog post unaltered._  If you want simple and reliable r2u just use r-ci.  If you mix and match and it breaks as it does here (no errror, but you get nonsensically repeated four identical results which wastes time off your 2000 min/months of free CI time at GH Actions (I think that is the budget).  Just run one instead.)

**Comment by eddelbuettel** [comment]
(Hi @eitsupi :  For you reference to isse 72, I don't follow what nanoarrow has to do with rpolars woes but maybe we leave that for another conversation.  For issue 80 it has always been CRAN Policy that you get at most two cores/threads. So `make -j 2` should address that.  Slower build.  But maybe still possible?   Anyway none of that really belongs here as this is after all the r2u repo :) )

**Comment by eitsupi** [comment]
Oh, and as for nanoarrow, I only mentioned it as an example of a dependency that was correctly identified on R-universe before nanoarrow was submitted to CRAN; it has nothing to do with why polars was removed from CRAN.
