### ISSUE TITLE
should `r-cran-pkgdown` depend on `pandoc` ?

### ISSUE THREAD

**Issue by lschneiderbauer** [rocker-org/r2u#5]
Hi,
thanks for your effort. I am just experimenting with rocker/r2u and it makes working with CI setups for R packages already so much easier and faster.

The issue: When using pkgdown, my CI job complains:
```
> pkgdown::build_site()
-- Installing package into temporary library -----------------------------------
== Building pkgdown site =======================================================
Reading from: '/builds/***'
Writing to:   '/builds/***/docs'
-- Initialising site -----------------------------------------------------------
Copying '../../../usr/lib/R/site-library/pkgdown/BS5/assets/link.svg' to 'link.svg'
Copying '../../../usr/lib/R/site-library/pkgdown/BS5/assets/pkgdown.js' to 'pkgdown.js'
-- Building home ---------------------------------------------------------------
Error: 
! in callr subprocess.
Caused by error in `convert_markdown_to_html(path, html_path)`:
! Pandoc not available
---
```

Now, installing pandoc solves the issue, but I wonder, should r-cran-pkgdown depend on pandoc?
Sorry in case this is not the right place for this issue.

**Comment by eddelbuettel** [comment]
(Without having looked into the specifics:)  I usually add dependencies to the meta-data r2u has in order build the packages.  Given that the dependency appears to be 'soft' for `rmarkdown` I have not.   

Stepping back a little, it is also tricky / sneaky as we often get `pandoc` in different ways.  The `rstudio` packages (desktop and server) bundle it, the `quarto` package does.  Plus in the past we also may have version issues (distro `pandoc` was too old, though not recently).

Lastly, it is just an `apt install pandoc` away.  The containers really are base layers for users to customize so on the margin I always lean against making them fatter.

Thoughts?

**Comment by eddelbuettel** [comment]
OTOH the [`rmarkdown` CRAN package](https://cloud.r-project.org/web/packages/rmarkdown/index.html) has a clear system dependency declared so you are quite right.  I may add it.

(Filing at the [r2u repo](https://github.com/eddelbuettel/r2u) would also have been fine.)

**Comment by eddelbuettel** [comment]
That was actually a valid feature request, and something I had not more generally implemented.  I had a single one-off for `rJava` to bring in the `default-jre`.  So I now added this via a new 'meta' control file where I can declare such _run-time_ dependencies (whereas we up until now cared about _build-time_ dependencies to let `dpkg` et al do their work to make packages fully _installable_.  This will now add a little extra run-time _convenience_.  

Two new `r-cran-rmarkdown` packages with suffix `.1.ca2?04.2` have been built, when you next `apt update; apt upgrade` you should see it come in.

Thanks for the suggestion!
