### ISSUE TITLE
pre-install git on rocker/r2u:24.04 machine?

### ISSUE THREAD

**Issue by Phylloxera** [rocker-org/r2u#7]
without it: `DEBIAN_FRONTEND=noninteractive installGithub.r Russel88/MicEco` gives Error: Failed to install 'MicEco' from GitHub:
  Git does not seem to be installed on your system.

**Comment by eddelbuettel** [comment]
We strike a balance between _general_ and useful, and compact enough.  `git` is not a program R commonly uses by default, the popularity of the `remotes::install_github()` function notwithstanding.

r2u is `apt` based and a quick `apt update -qq; apt install git` is easy enough.  I hope you understand our reasoning.
